# fly.toml app configuration file generated for metadata-api on 2024-07-25T19:14:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metadata-api'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ALLOWED_METHODS="GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS"
  ALLOWED_ORIGIN="http://localhost:3001,http://localhost:3000,*"
  ALLOWED_HEADERS="Content-Type, Authorization"
  EXPOSED_HEADERS=""
  MAX_AGE="86400"
  CREDENTIALS="true"
